#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum UiLanguage {
    #[default]
    English = 0,
    Spanish = 1,
    French = 2,
    German = 3,
    Romanian = 4,
    Polish = 5,
}

impl UiLanguage {
    pub const COUNT: usize = 6;

    pub fn from_u8(value: u8) -> Self {
        match value {
            0 => Self::English,
            1 => Self::Spanish,
            2 => Self::French,
            3 => Self::German,
            4 => Self::Romanian,
            5 => Self::Polish,
            _ => Self::English,
        }
    }

    pub fn next(self) -> Self {
        Self::from_u8((self as u8 + 1) % Self::COUNT as u8)
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::English => "English",
            Self::Spanish => "Español",
            Self::French => "Français",
            Self::German => "Deutsch",
            Self::Romanian => "Română",
            Self::Polish => "Polski",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum UiText {
    Resume = 0,
    Chapters,
    Library,
    Settings,
    UsbTransfer,
    PowerOff,
    Back,
    Display,
    TypographyTune,
    WordPacing,
    Theme,
    Brightness,
    Language,
    ReadingMode,
    LongWords,
    Complexity,
    Punctuation,
    ResetPacing,
    Night,
    Dark,
    Light,
    On,
    Off,
    FontSize,
    Typeface,
    PhantomWords,
    RedHighlight,
    Tracking,
    Anchor,
    GuideWidth,
    GuideGap,
    Reset,
    Typography,
    TapToExit,
    TapToReset,
    TapChangeSample,
    TapExitSample,
    TapToggleSample,
    TapCycleSample,
    CurrentBook,
    Start,
    StartOfBook,
    RestartBook,
    AreYouSure,
    NoKeepPlace,
    YesRestart,
    NoSamples,
    Large,
    Medium,
    Small,
    Standard,
    RsvpMode,
    ScrollMode,
    TimeEstimate,
    TimeEstimateAccurate,
    TimeEstimateFast,
}

// English strings for all UiText variants.
static STRINGS_EN: &[&str] = &[
    "Resume",
    "Chapters",
    "Library",
    "Settings",
    "USB Transfer",
    "Power Off",
    "Back",
    "Display",
    "Typography Tune",
    "Word Pacing",
    "Theme",
    "Brightness",
    "Language",
    "Reading Mode",
    "Long Words",
    "Complexity",
    "Punctuation",
    "Reset Pacing",
    "Night",
    "Dark",
    "Light",
    "On",
    "Off",
    "Font Size",
    "Typeface",
    "Phantom Words",
    "Red Highlight",
    "Tracking",
    "Anchor",
    "Guide Width",
    "Guide Gap",
    "Reset",
    "Typography",
    "Tap to Exit",
    "Tap to Reset",
    "Tap to Change",
    "Tap to Exit",
    "Tap to Toggle",
    "Tap to Cycle",
    "Current Book",
    "Start",
    "Start of Book",
    "Restart Book",
    "Are you sure?",
    "No, keep place",
    "Yes, restart",
    "No samples",
    "Large",
    "Medium",
    "Small",
    "Standard",
    "RSVP Mode",
    "Scroll Mode",
    "Time estimate",
    "Time estimate (accurate)",
    "Time estimate (fast)",
];

// Spanish
static STRINGS_ES: &[&str] = &[
    "Continuar",
    "Capítulos",
    "Biblioteca",
    "Ajustes",
    "Transfer. USB",
    "Apagar",
    "Volver",
    "Pantalla",
    "Ajuste tipogr.",
    "Ritmo palabras",
    "Tema",
    "Brillo",
    "Idioma",
    "Modo lectura",
    "Palabras largas",
    "Complejidad",
    "Puntuación",
    "Reset ritmo",
    "Noche",
    "Oscuro",
    "Claro",
    "Sí",
    "No",
    "Tamaño fuente",
    "Tipografía",
    "Palabras fantasma",
    "Resaltado rojo",
    "Tracking",
    "Ancla",
    "Ancho guía",
    "Gap guía",
    "Reset",
    "Tipografía",
    "Toca p/salir",
    "Toca p/reset",
    "Toca p/cambiar",
    "Toca p/salir",
    "Toca p/alternar",
    "Toca p/ciclar",
    "Libro actual",
    "Iniciar",
    "Inicio del libro",
    "Reiniciar libro",
    "¿Estás seguro?",
    "No, guardar posición",
    "Sí, reiniciar",
    "Sin muestras",
    "Grande",
    "Mediano",
    "Pequeño",
    "Estándar",
    "Modo RSVP",
    "Modo scroll",
    "Estimación tiempo",
    "Estimación (precisa)",
    "Estimación (rápida)",
];

// French
static STRINGS_FR: &[&str] = &[
    "Reprendre",
    "Chapitres",
    "Bibliothèque",
    "Réglages",
    "Transfert USB",
    "Éteindre",
    "Retour",
    "Affichage",
    "Régl. typo",
    "Rythme mots",
    "Thème",
    "Luminosité",
    "Langue",
    "Mode lecture",
    "Mots longs",
    "Complexité",
    "Ponctuation",
    "Reset rythme",
    "Nuit",
    "Sombre",
    "Clair",
    "Oui",
    "Non",
    "Taille police",
    "Police",
    "Mots fantômes",
    "Surlignage rouge",
    "Tracking",
    "Ancre",
    "Largeur guide",
    "Gap guide",
    "Reset",
    "Typographie",
    "Appuyer pour quitter",
    "Appuyer pour reset",
    "Appuyer changer",
    "Appuyer quitter",
    "Appuyer basculer",
    "Appuyer cycler",
    "Livre actuel",
    "Démarrer",
    "Début du livre",
    "Recommencer",
    "Êtes-vous sûr?",
    "Non, garder",
    "Oui, recommencer",
    "Pas d'exemples",
    "Grand",
    "Moyen",
    "Petit",
    "Standard",
    "Mode RSVP",
    "Mode défilement",
    "Estimation temps",
    "Estimation (précise)",
    "Estimation (rapide)",
];

// German
static STRINGS_DE: &[&str] = &[
    "Fortsetzen",
    "Kapitel",
    "Bibliothek",
    "Einstellungen",
    "USB-Transfer",
    "Ausschalten",
    "Zurück",
    "Anzeige",
    "Typo-Einstellung",
    "Wort-Rhythmus",
    "Thema",
    "Helligkeit",
    "Sprache",
    "Lesemodus",
    "Lange Wörter",
    "Komplexität",
    "Interpunktion",
    "Rhythmus zurücksetzen",
    "Nacht",
    "Dunkel",
    "Hell",
    "Ein",
    "Aus",
    "Schriftgröße",
    "Schrift",
    "Phantomwörter",
    "Rote Markierung",
    "Tracking",
    "Anker",
    "Führungsbreite",
    "Führungsabstand",
    "Zurücksetzen",
    "Typografie",
    "Tippen zum Beenden",
    "Tippen zum Zurücksetzen",
    "Tippen wechseln",
    "Tippen beenden",
    "Tippen umschalten",
    "Tippen durchlaufen",
    "Aktuelles Buch",
    "Starten",
    "Buchanfang",
    "Buch neu starten",
    "Sind Sie sicher?",
    "Nein, behalten",
    "Ja, neu starten",
    "Keine Beispiele",
    "Groß",
    "Mittel",
    "Klein",
    "Standard",
    "RSVP-Modus",
    "Scroll-Modus",
    "Zeitschätzung",
    "Zeitschätzung (genau)",
    "Zeitschätzung (schnell)",
];

// Romanian
static STRINGS_RO: &[&str] = &[
    "Continuă",
    "Capitole",
    "Bibliotecă",
    "Setări",
    "Transfer USB",
    "Oprire",
    "Înapoi",
    "Afișaj",
    "Ajust. tipogr.",
    "Ritm cuvinte",
    "Temă",
    "Luminozitate",
    "Limbă",
    "Mod citire",
    "Cuvinte lungi",
    "Complexitate",
    "Punctuație",
    "Reset ritm",
    "Noapte",
    "Întunecat",
    "Luminos",
    "Da",
    "Nu",
    "Dim. font",
    "Font",
    "Cuvinte fantomă",
    "Evidențiere roșie",
    "Tracking",
    "Ancoră",
    "Lățime ghid",
    "Spațiu ghid",
    "Reset",
    "Tipografie",
    "Atinge p/ieșire",
    "Atinge p/reset",
    "Atinge p/schimba",
    "Atinge p/ieșire",
    "Atinge p/comuta",
    "Atinge p/cicla",
    "Cartea curentă",
    "Start",
    "Începutul cărții",
    "Restartare carte",
    "Ești sigur?",
    "Nu, păstrează locul",
    "Da, restart",
    "Fără exemple",
    "Mare",
    "Mediu",
    "Mic",
    "Standard",
    "Mod RSVP",
    "Mod scroll",
    "Estimare timp",
    "Estimare (precisă)",
    "Estimare (rapidă)",
];

// Polish
static STRINGS_PL: &[&str] = &[
    "Wznów",
    "Rozdziały",
    "Biblioteka",
    "Ustawienia",
    "Transfer USB",
    "Wyłącz",
    "Wstecz",
    "Wyświetlacz",
    "Nastaw. typogr.",
    "Rytm słów",
    "Motyw",
    "Jasność",
    "Język",
    "Tryb czytania",
    "Długie słowa",
    "Złożoność",
    "Interpunkcja",
    "Reset rytmu",
    "Noc",
    "Ciemny",
    "Jasny",
    "Wł.",
    "Wył.",
    "Rozmiar czcionki",
    "Czcionka",
    "Słowa fantomy",
    "Czerwone podś.",
    "Tracking",
    "Kotwica",
    "Szer. prowadnicy",
    "Przerwa prowadnicy",
    "Zresetuj",
    "Typografia",
    "Dotknij aby wyjść",
    "Dotknij aby reset",
    "Dotknij zmień",
    "Dotknij wyjdź",
    "Dotknij przełącz",
    "Dotknij przejdź",
    "Bieżąca książka",
    "Start",
    "Początek książki",
    "Restart książki",
    "Jesteś pewny?",
    "Nie, zachowaj miejsce",
    "Tak, restart",
    "Brak próbek",
    "Duży",
    "Średni",
    "Mały",
    "Standardowy",
    "Tryb RSVP",
    "Tryb scroll",
    "Szacowanie czasu",
    "Szacowanie (dokładne)",
    "Szacowanie (szybkie)",
];

pub fn get_string(lang: UiLanguage, text: UiText) -> &'static str {
    let idx = text as usize;
    let table: &[&str] = match lang {
        UiLanguage::English => STRINGS_EN,
        UiLanguage::Spanish => STRINGS_ES,
        UiLanguage::French => STRINGS_FR,
        UiLanguage::German => STRINGS_DE,
        UiLanguage::Romanian => STRINGS_RO,
        UiLanguage::Polish => STRINGS_PL,
    };
    table.get(idx).copied().unwrap_or("")
}
